updated script for role

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -2,18 +2,19 @@ name: 'AWS Security Group IP Modifier'
 description: 'Add or remove an IP to/from an AWS security group'
 
 inputs:
-  all-sec:
-    required: true
-    description: 'All AWS credentials as secrets (e.g., AWS_ACCESS_KEY_900, AWS_SECRET_ACCESS_KEY_900, etc.)'
-  account:
+  # all-sec:
+  #   required: true
+  #   description: 'All AWS credentials as secrets (e.g., AWS_ACCESS_KEY_900, AWS_SECRET_ACCESS_KEY_900, etc.)'
+  account-id:
     required: true
     description: 'Account ID to use for AWS keys'
-  aws-access-key-id:
-    required: false
-    description: 'AWS Access Key ID'
-  aws-secret-access-key:
-    required: false
-    description: 'AWS Secret Access Key'
+  # aws-access-key-id:
+  #   required: false
+  #   description: 'AWS Access Key ID'
+  # aws-secret-access-key:
+  #   required: false
+  #   description: 'AWS Secret Access Key'
+
   aws-region:
     required: true
     description: 'AWS Region (e.g., us-east-1)'
@@ -39,7 +40,6 @@ inputs:
   action:
     required: true
     description: 'Action to perform: add or remove IP'
-
 runs:
   using: 'composite'
   steps:
@@ -51,42 +51,39 @@ runs:
   - name: Install dependencies
     run: |
       python -m pip install --upgrade pip
-      pip install boto3 requests python-dotenv
+      pip install boto3 requests
     shell: bash
 
-  - name: Run Python script to modify security group
+  - name: Select IAM Role ARN
+    id: select-role
     run: |
-      export AWS_ACCESS_KEY_ID="${{ inputs.aws-access-key-id }}"
-      export AWS_SECRET_ACCESS_KEY="${{ inputs.aws-secret-access-key }}"
+      case "${{ inputs.account-id }}" in
+        365)
+          echo "ROLE_ARN=${{ secrets.AWS_ROLE_ARN_365 }}" >> $GITHUB_ENV
+          ;;
+        019)
+          echo "ROLE_ARN=${{ secrets.AWS_ROLE_ARN_019 }}" >> $GITHUB_ENV
+          ;;
+        *)
+          echo "Invalid accountid"
+          exit 1
+          ;;
+      esac
 
+  - name: Configure AWS credentials via OIDC
+    uses: aws-actions/configure-aws-credentials@v4
+    with:
+      role-to-assume: ${{ env.ROLE_ARN }}
+      aws-region: ${{ inputs.aws-region }}
+
+  - name: Run Python script
+    run: |
       TO_PORT_ARG=""
       if [ -n "${{ inputs.to-port }}" ]; then
         TO_PORT_ARG="--to-port ${{ inputs.to-port }}"
       fi
 
-      echo "${{ inputs.all-sec }}" > val.env
-      source val.env
-
-      account="${{ inputs.account }}"
-
-      # Dynamically choose the correct AWS keys based on account
-      access_key_var="AWS_ACCESS_KEY_${account}"
-      secret_key_var="AWS_SECRET_ACCESS_KEY_${account}"
-
-      access_key_value=$(eval echo \$$access_key_var)
-      secret_key_value=$(eval echo \$$secret_key_var)
-
-      if [[ -z "$access_key_value" || -z "$secret_key_value" ]]; then
-        echo " Missing keys for account $account"
-        exit 1
-      fi
-
-      export AWS_ACCESS_KEY_ID="$access_key_value"
-      export AWS_SECRET_ACCESS_KEY="$secret_key_value"
-
-      # Call your Python script to modify the security group
       python3 "${{ github.action_path }}/main.py" \
-        --account ${{ inputs.account }} \
         --action ${{ inputs.action }} \
         --security-group-id ${{ inputs.security-group-id }} \
         --port ${{ inputs.port }} \
