Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -2,18 +2,18 @@ name: 'AWS Security Group IP Modifier'
 description: 'Add or remove an IP to/from an AWS security group'
 
 inputs:
-  all-sec:
-    required: true
-    description: 'All AWS credentials as secrets (e.g., AWS_ACCESS_KEY_900, AWS_SECRET_ACCESS_KEY_900, etc.)'
+  # all-sec:
+  #   required: true
+  #   description: 'All AWS credentials as secrets (e.g., AWS_ACCESS_KEY_900, AWS_SECRET_ACCESS_KEY_900, etc.)'
   account-id:
     required: true
     description: 'Account ID to use for AWS keys'
-  aws-access-key-id:
-    required: false
-    description: 'AWS Access Key ID'
-  aws-secret-access-key:
-    required: false
-    description: 'AWS Secret Access Key'
+  # aws-access-key-id:
+  #   required: false
+  #   description: 'AWS Access Key ID'
+  # aws-secret-access-key:
+  #   required: false
+  #   description: 'AWS Secret Access Key'
 
   aws-region:
     required: true
@@ -54,28 +54,28 @@ runs:
       pip install boto3 requests
     shell: bash
 
-  # - name: Select IAM Role ARN
-  #   id: select-role
-  #   run: |
-  #     case "${{ inputs.account-id }}" in
-  #       365)
-  #         echo "ROLE_ARN=${{ secrets.AWS_ROLE_ARN_365 }}" >> $GITHUB_ENV
-  #         ;;
-  #       019)
-  #         echo "ROLE_ARN=${{ secrets.AWS_ROLE_ARN_019 }}" >> $GITHUB_ENV
-  #         ;;
-  #       *)
-  #         echo "Invalid accountid"
-  #         exit 1
-  #         ;;
-  #     esac
-  #   shell: bash
+  - name: Select IAM Role ARN
+    id: select-role
+    run: |
+      case "${{ inputs.account-id }}" in
+        365)
+          echo "ROLE_ARN=${{ secrets.AWS_ROLE_ARN_365 }}" >> $GITHUB_ENV
+          ;;
+        019)
+          echo "ROLE_ARN=${{ secrets.AWS_ROLE_ARN_019 }}" >> $GITHUB_ENV
+          ;;
+        *)
+          echo "Invalid accountid"
+          exit 1
+          ;;
+      esac
+    shell: bash
 
-  # - name: Configure AWS credentials via OIDC
-  #   uses: aws-actions/configure-aws-credentials@v6
-  #   with:
-  #     role-to-assume: ${{ env.ROLE_ARN }}
-  #     aws-region: ${{ inputs.aws-region }}
+  - name: Configure AWS credentials via OIDC
+    uses: aws-actions/configure-aws-credentials@v6
+    with:
+      role-to-assume: ${{ env.ROLE_ARN }}
+      aws-region: ${{ inputs.aws-region }}
 
   - name: Run Python script
     run: |
